### ISSUE TITLE
GlobalProtect logs sometimes cannot parse private IP field

### ISSUE THREAD

**Issue by btorresgil** [PaloAltoNetworks/Splunk_TA_paloalto#34]
When the `Private IP` field is the last field, the description field ends with a period `.` which is incorrectly interpreted as part of the IP address.  Need to adjust the regex parser for this field to ignore the final period in the field.

Example:

    SomeField: SomeValue, Private IP: 10.0.0.1.

(notice the period at the end of the IP address in this example)

**Comment by paulmnguyen** [comment]
Workaround until we get this bug fixed in the next release:

In SPLUNK_HOME/apps/Splunk_TA_paloalto/default/transforms.conf
 
You need to modify line: 186
From:
REGEX = Private IP: (?<src_ip>[^,]+)
To:
REGEX = Private IP: (?<src_ip>(?:\d{1,3}\.){3}\d{1,3}+)
 
Do the same for line: 190
From:
REGEX = Login from: (?<src_ip>[^,]+)
To:
REGEX = Login from: (?<src_ip>(?:\d{1,3}\.){3}\d{1,3}+)

**Comment by paulmnguyen** [comment]
This is fixed in 6.1.1
