### ISSUE TITLE
Web Data Model `category` CIM alias to Palo Alto `http_category`

### ISSUE THREAD

**Issue by simonsigre** [PaloAltoNetworks/Splunk_TA_paloalto#35]
Looking at previous commits the CIM field `category` looks to be linked to `threat_category` ( https://github.com/PaloAltoNetworks/Splunk_TA_paloalto/commit/60cedc5d03b1fbd821a7ac4c03b6eab861e62cae) 

The Splunk CIM v4.12 defines (for the `web` datamodel) ;
```The category of traffic, such as may be provided by a proxy server.```

As such I believe this infers this should be linked to traditional URL categories (or customised ones) which means the alias for;

`index=*  sourcetype="pan:threat" log_subtype=url`   should be `category` aliased to `http_category`

Happy to do this via a merge if easier (and agreed)

**Comment by btorresgil** [comment]
For URL logs, category is raw_category is http_category. They are all the same, so I believe this is correct.  Let me know if you see incorrect results for the category field of URL logs on the latest app version. It should contain the http category.

**Comment by simonsigre** [comment]
Ahh I see by the notes of 6.1 release `Version 6.1.0 - Fix: category field for URL logs is now more consistent` not sure how I missed this.   This version is still being vetted for Splunk Cloud (we are pushing) .
I will wait for that and then test further.

I can confirm that in `6.0.2` (current Splunk Cloud version) this was not the case (see screenshot) 
![screenshot from 2018-11-04 08-42-20](https://user-images.githubusercontent.com/14932913/47957641-e1113c80-e00d-11e8-8eed-aadfb55afad5.png)

**Comment by btorresgil** [comment]
Gotcha, yeah fixed in 6.1. Splunk Cloud certification should complete soon. In the meantime you can borrow the line from that commit as a workaround to fix the issue.  Change it in your props.conf.  For Splunk Cloud you might need to open a ticket for this since there’s no direct access to files.

I’ll close this out, but thanks for checking!  Always feel free to open issues if there are improvements we can make.
